import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import type { Invariant, ChainStep, BrandStyle } from '../spec/types.js';

export interface GeneratorOptions {
  outputDir: string;
  brandStyle?: BrandStyle;
}

export function generateGuards(invariants: Invariant[], options: GeneratorOptions): void {
  const { outputDir, brandStyle = 'symbol' } = options;

  // Create output directory
  mkdirSync(outputDir, { recursive: true });

  // Generate guard files for each invariant
  const guardFiles: string[] = [];
  for (const invariant of invariants) {
    const guardName = invariant.name;
    const fileName = guardName;

    generateGuardDeclaration(invariant, outputDir, fileName, brandStyle);
    generateGuardImplementation(invariant, outputDir, fileName);

    guardFiles.push(fileName);
  }

  // Generate barrel export
  generateBarrelExport(guardFiles, outputDir);
}

function generateGuardDeclaration(
  invariant: Invariant,
  outputDir: string,
  fileName: string,
  brandStyle: BrandStyle
): void {
  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * Guard: ${invariant.name}`);
  lines.push(` * ${invariant.description}`);
  lines.push(` * `);
  lines.push(` * This file is auto-generated by VerifyLoop. Do not edit manually.`);
  lines.push(` */`);
  lines.push('');

  // Brand type definition (symbol style only for v1)
  if (brandStyle === 'symbol') {
    lines.push(`declare const __brand: unique symbol;`);
    lines.push(`type Brand<T, TBrand extends string> = T & { readonly [__brand]: TBrand };`);
    lines.push('');
  }

  // Generate type for each chain step
  for (const step of invariant.chain) {
    lines.push(`/**`);
    lines.push(` * ${step.description}`);
    if (step.requires) {
      lines.push(` * Requires: ${step.requires}`);
    }
    lines.push(` */`);

    if (step.fields && Object.keys(step.fields).length > 0) {
      // Type with fields
      lines.push(`export type ${step.type} = Brand<{`);
      for (const [fieldName, fieldType] of Object.entries(step.fields)) {
        lines.push(`  ${fieldName}: ${fieldType};`);
      }
      lines.push(`}, '${step.type}'>;`);
    } else {
      // Opaque type without fields
      lines.push(`export type ${step.type} = Brand<Record<string, never>, '${step.type}'>;`);
    }
    lines.push('');
  }

  // Generate constructor signatures
  lines.push(`// Constructors`);
  for (const step of invariant.chain) {
    const params: string[] = [];

    if (step.requires) {
      params.push(`input: ${step.requires}`);
    }

    if (step.fields && Object.keys(step.fields).length > 0) {
      for (const [fieldName, fieldType] of Object.entries(step.fields)) {
        if (!step.requires || !fieldName.includes('input')) {
          params.push(`${fieldName}: ${fieldType}`);
        }
      }
    }

    lines.push(`export declare function ${step.constructor}(${params.join(', ')}): ${step.type};`);
  }
  lines.push('');

  // Generate protected function signatures
  if (invariant.protected_functions.length > 0) {
    lines.push(`// Protected functions`);
    for (const fnName of invariant.protected_functions) {
      // Find the last type in the chain (most restrictive)
      const lastStep = invariant.chain[invariant.chain.length - 1];
      lines.push(`export declare function ${fnName}(input: ${lastStep.type}, ...args: unknown[]): Promise<unknown>;`);
    }
  }

  const filePath = join(outputDir, `${fileName}.d.ts`);
  writeFileSync(filePath, lines.join('\n'));
}

function generateGuardImplementation(
  invariant: Invariant,
  outputDir: string,
  fileName: string
): void {
  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * Guard Implementation: ${invariant.name}`);
  lines.push(` * ${invariant.description}`);
  lines.push(` * `);
  lines.push(` * This file is auto-generated by VerifyLoop.`);
  lines.push(` * Fill in the constructor implementations with your business logic.`);
  lines.push(` */`);
  lines.push('');

  // Import types from declaration file
  lines.push(`import type {`);
  for (const step of invariant.chain) {
    lines.push(`  ${step.type},`);
  }
  lines.push(`} from './${fileName}.js';`);
  lines.push('');

  // Generate constructor stubs
  for (const step of invariant.chain) {
    const params: string[] = [];

    if (step.requires) {
      params.push(`input: ${step.requires}`);
    }

    if (step.fields && Object.keys(step.fields).length > 0) {
      for (const [fieldName, fieldType] of Object.entries(step.fields)) {
        if (!step.requires || !fieldName.includes('input')) {
          params.push(`${fieldName}: ${fieldType}`);
        }
      }
    }

    lines.push(`/**`);
    lines.push(` * ${step.description}`);
    lines.push(` */`);
    lines.push(`export function ${step.constructor}(${params.join(', ')}): ${step.type} {`);
    lines.push(`  // TODO: Implement ${step.constructor}`);
    lines.push(`  // This is a stub - add your validation/transformation logic here`);
    if (step.requires) {
      lines.push(`  return input as ${step.type};`);
    } else {
      lines.push(`  return {} as ${step.type};`);
    }
    lines.push(`}`);
    lines.push('');
  }

  // Generate protected function wrappers
  if (invariant.protected_functions.length > 0) {
    lines.push(`// Protected function wrappers`);
    lines.push(`// These functions enforce that the input has passed through the full chain`);
    lines.push('');

    for (const fnName of invariant.protected_functions) {
      const lastStep = invariant.chain[invariant.chain.length - 1];
      lines.push(`/**`);
      lines.push(` * Protected function: ${fnName}`);
      lines.push(` * Requires input of type: ${lastStep.type}`);
      lines.push(` */`);
      lines.push(`export async function ${fnName}(input: ${lastStep.type}, ...args: unknown[]): Promise<unknown> {`);
      lines.push(`  // TODO: Implement ${fnName}`);
      lines.push(`  // This function can only be called with fully validated input`);
      lines.push(`  throw new Error('${fnName} not implemented');`);
      lines.push(`}`);
      lines.push('');
    }
  }

  const filePath = join(outputDir, `${fileName}.ts`);
  writeFileSync(filePath, lines.join('\n'));
}

function generateBarrelExport(guardFiles: string[], outputDir: string): void {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Barrel export for all guards`);
  lines.push(` * Auto-generated by VerifyLoop`);
  lines.push(` */`);
  lines.push('');

  for (const file of guardFiles) {
    lines.push(`export * from './${file}.js';`);
  }

  const filePath = join(outputDir, 'index.ts');
  writeFileSync(filePath, lines.join('\n'));
}
