import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Invariant, BrandStyle } from '../spec/types.js';

export interface GeneratorOptions {
  outputDir: string;
  brandStyle?: BrandStyle;
}

export function generateGuards(invariants: Invariant[], options: GeneratorOptions): void {
  const { outputDir, brandStyle = 'symbol' } = options;

  // Create output directory
  mkdirSync(outputDir, { recursive: true });

  // Generate guard files for each invariant
  const guardFiles: string[] = [];
  for (const invariant of invariants) {
    const guardName = invariant.name;
    const fileName = guardName;

    generateGuardDeclaration(invariant, outputDir, fileName, brandStyle);
    generateGuardImplementation(invariant, outputDir, fileName);

    guardFiles.push(fileName);
  }

  // Generate barrel export
  generateBarrelExport(guardFiles, outputDir);
}

function generateGuardDeclaration(
  invariant: Invariant,
  outputDir: string,
  fileName: string,
  brandStyle: BrandStyle
): void {
  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * Guard: ${invariant.name}`);
  lines.push(` * ${invariant.description}`);
  lines.push(` * `);
  lines.push(` * This file is auto-generated by VerifyLoop. Do not edit manually.`);
  lines.push(` */`);
  lines.push('');

  // Brand type definition (symbol style only for v1)
  if (brandStyle === 'symbol') {
    lines.push(`declare const __brand: unique symbol;`);
    lines.push(`type Brand<T, TBrand extends string> = T & { readonly [__brand]: TBrand };`);
    lines.push('');
  }

  // Generate type for each chain step
  for (const step of invariant.chain) {
    lines.push(`/**`);
    lines.push(` * ${step.description}`);
    if (step.requires) {
      lines.push(` * Requires: ${step.requires}`);
    }
    lines.push(` */`);

    if (step.fields && Object.keys(step.fields).length > 0) {
      // Type with fields
      lines.push(`export type ${step.type} = Brand<{`);
      for (const [fieldName, fieldType] of Object.entries(step.fields)) {
        lines.push(`  ${fieldName}: ${fieldType};`);
      }
      lines.push(`}, '${step.type}'>;`);
    } else {
      // Opaque type without fields
      lines.push(`export type ${step.type} = Brand<Record<string, never>, '${step.type}'>;`);
    }
    lines.push('');
  }

  // Generate constructor signatures
  lines.push(`// Constructors`);
  for (let i = 0; i < invariant.chain.length; i++) {
    const step = invariant.chain[i];
    const params: string[] = [];

    if (!step.requires) {
      // First step - no requires, use all fields as params
      if (step.fields && Object.keys(step.fields).length > 0) {
        for (const [fieldName, fieldType] of Object.entries(step.fields)) {
          params.push(`${fieldName}: ${fieldType}`);
        }
      }
    } else {
      // Has requires - determine new fields only
      params.push(`input: ${step.requires}`);

      if (step.fields && Object.keys(step.fields).length > 0) {
        // Get previous step's field names
        const prevStep = invariant.chain[i - 1];
        const prevFieldNames = new Set<string>(
          prevStep.fields ? Object.keys(prevStep.fields) : []
        );

        const thisFieldNames = Object.keys(step.fields);

        // Determine carry-forward and added fields
        const carryForwardFields = thisFieldNames.filter(name => prevFieldNames.has(name));
        const addedFields = thisFieldNames.filter(name => !prevFieldNames.has(name));

        // If any fields carry forward, add the new fields as params
        if (carryForwardFields.length > 0) {
          for (const fieldName of addedFields) {
            params.push(`${fieldName}: ${step.fields[fieldName]}`);
          }
        }
        // If no fields carry forward, all fields are derived/transformed
        // No extra params needed
      }
    }

    lines.push(`export declare function ${step.constructor}(${params.join(', ')}): ${step.type};`);
  }
  lines.push('');

  // Generate protected function signatures
  if (invariant.protected_functions.length > 0) {
    lines.push(`// Protected functions`);
    for (const fnName of invariant.protected_functions) {
      // Find the last type in the chain (most restrictive)
      const lastStep = invariant.chain[invariant.chain.length - 1];
      lines.push(`export declare function ${fnName}(input: ${lastStep.type}, ...args: unknown[]): Promise<unknown>;`);
    }
  }

  const filePath = join(outputDir, `${fileName}.d.ts`);
  writeFileSync(filePath, lines.join('\n'));
}

function generateGuardImplementation(
  invariant: Invariant,
  outputDir: string,
  fileName: string
): void {
  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * Guard Implementation: ${invariant.name}`);
  lines.push(` * ${invariant.description}`);
  lines.push(` * `);
  lines.push(` * This file is auto-generated by VerifyLoop.`);
  lines.push(` * Fill in the constructor implementations with your business logic.`);
  lines.push(` */`);
  lines.push('');

  // Import types from declaration file
  lines.push(`import type {`);
  for (const step of invariant.chain) {
    lines.push(`  ${step.type},`);
  }
  lines.push(`} from './${fileName}.d.js';`);
  lines.push('');

  // Re-export types for consumers
  lines.push(`export type {`);
  for (const step of invariant.chain) {
    lines.push(`  ${step.type},`);
  }
  lines.push(`} from './${fileName}.d.js';`);
  lines.push('');

  // Generate constructor stubs
  for (let i = 0; i < invariant.chain.length; i++) {
    const step = invariant.chain[i];
    const params: string[] = [];

    if (!step.requires) {
      // First step - no requires, use all fields as params
      if (step.fields && Object.keys(step.fields).length > 0) {
        for (const [fieldName, fieldType] of Object.entries(step.fields)) {
          params.push(`${fieldName}: ${fieldType}`);
        }
      }
    } else {
      // Has requires - determine new fields only
      params.push(`input: ${step.requires}`);

      if (step.fields && Object.keys(step.fields).length > 0) {
        // Get previous step's field names
        const prevStep = invariant.chain[i - 1];
        const prevFieldNames = new Set<string>(
          prevStep.fields ? Object.keys(prevStep.fields) : []
        );

        const thisFieldNames = Object.keys(step.fields);

        // Determine carry-forward and added fields
        const carryForwardFields = thisFieldNames.filter(name => prevFieldNames.has(name));
        const addedFields = thisFieldNames.filter(name => !prevFieldNames.has(name));

        // If any fields carry forward, add the new fields as params
        if (carryForwardFields.length > 0) {
          for (const fieldName of addedFields) {
            params.push(`${fieldName}: ${step.fields[fieldName]}`);
          }
        }
        // If no fields carry forward, all fields are derived/transformed
        // No extra params needed
      }
    }

    lines.push(`/**`);
    lines.push(` * ${step.description}`);
    lines.push(` */`);
    lines.push(`export function ${step.constructor}(${params.join(', ')}): ${step.type} {`);
    lines.push(`  // TODO: Implement ${step.constructor}`);

    // Determine return statement based on field structure
    if (!step.requires) {
      // First step - construct object from params
      if (step.fields && Object.keys(step.fields).length > 0) {
        lines.push(`  return {`);
        for (const [fieldName] of Object.entries(step.fields)) {
          lines.push(`    ${fieldName},`);
        }
        lines.push(`  } as ${step.type};`);
      } else {
        lines.push(`  return {} as ${step.type};`);
      }
    } else {
      // Has requires
      if (step.fields && Object.keys(step.fields).length > 0) {
        const prevStep = invariant.chain[i - 1];
        const prevFieldNames = new Set<string>(
          prevStep.fields ? Object.keys(prevStep.fields) : []
        );

        const thisFieldNames = Object.keys(step.fields);
        const carryForwardFields = thisFieldNames.filter(name => prevFieldNames.has(name));
        const addedFields = thisFieldNames.filter(name => !prevFieldNames.has(name));

        if (carryForwardFields.length === 0) {
          // All fields are derived/transformed - extract from input
          lines.push(`  // Extract and validate fields from input`);
          lines.push(`  return input as any as ${step.type};`);
        } else {
          // Fields carry forward - merge input with new params
          if (addedFields.length > 0) {
            lines.push(`  return { ...input, ${addedFields.join(', ')} } as any as ${step.type};`);
          } else {
            // No new fields, just transformation
            lines.push(`  return input as any as ${step.type};`);
          }
        }
      } else {
        // No fields, only transformation
        lines.push(`  return input as any as ${step.type};`);
      }
    }
    lines.push(`}`);
    lines.push('');
  }

  // Generate protected function wrappers
  if (invariant.protected_functions.length > 0) {
    lines.push(`// Protected function wrappers`);
    lines.push(`// These functions enforce that the input has passed through the full chain`);
    lines.push('');

    for (const fnName of invariant.protected_functions) {
      const lastStep = invariant.chain[invariant.chain.length - 1];
      lines.push(`/**`);
      lines.push(` * Protected function: ${fnName}`);
      lines.push(` * Requires input of type: ${lastStep.type}`);
      lines.push(` */`);
      lines.push(`export async function ${fnName}(input: ${lastStep.type}, ...args: unknown[]): Promise<unknown> {`);
      lines.push(`  // TODO: Implement ${fnName}`);
      lines.push(`  // This function can only be called with fully validated input`);
      lines.push(`  throw new Error('${fnName} not implemented');`);
      lines.push(`}`);
      lines.push('');
    }
  }

  const filePath = join(outputDir, `${fileName}.ts`);
  writeFileSync(filePath, lines.join('\n'));
}

function generateBarrelExport(guardFiles: string[], outputDir: string): void {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Barrel export for all guards`);
  lines.push(` * Auto-generated by VerifyLoop`);
  lines.push(` */`);
  lines.push('');

  for (const file of guardFiles) {
    lines.push(`export * from './${file}.js';`);
  }

  const filePath = join(outputDir, 'index.ts');
  writeFileSync(filePath, lines.join('\n'));
}
