"""
Episode construction: group messages by session, summarize with Haiku.

Episode boundaries are determined by conversation session_id — each unique
session becomes one or more episodes depending on size. Within a session,
messages are grouped into blocks (default: up to BLOCK_SIZE messages), and
each block gets a summary generated by Haiku.
"""

from __future__ import annotations

from typing import List, Optional

from xmemory._llm import HAIKU_MODEL, call_llm
from xmemory.models import Episode, Message
from xmemory.store import MemoryStore

# How many messages to include in a single episode block.
# Can be overridden per call.
DEFAULT_BLOCK_SIZE = 10


def _build_summary_prompt(messages: List[Message]) -> str:
    turns = "\n".join(
        f"[{m.timestamp.isoformat()}] {m.content}" for m in messages
    )
    return (
        "You are summarizing a block of conversation messages for a memory system.\n\n"
        "Create a concise summary (2-4 sentences) that captures:\n"
        "- The main topics discussed\n"
        "- Any decisions made\n"
        "- Key facts mentioned\n"
        "- Participants or context if clear\n\n"
        "Conversation block:\n"
        f"{turns}\n\n"
        "Summary:"
    )


def summarize_block(
    messages: List[Message],
    model: str = HAIKU_MODEL,
    client=None,
) -> str:
    """Generate a summary for a block of messages using Haiku."""
    prompt = _build_summary_prompt(messages)
    return call_llm(prompt, model=model, max_tokens=256, client=client).strip()


def construct_episodes(
    store: MemoryStore,
    session_id: Optional[str] = None,
    block_size: int = DEFAULT_BLOCK_SIZE,
    model: str = HAIKU_MODEL,
    client=None,
) -> List[Episode]:
    """
    Group unprocessed messages into episodes and persist them.

    For each unique session_id (or the specified one), messages are chunked
    into blocks of `block_size`. Each block is summarised by Haiku and stored
    as an Episode. The messages are then updated to point to their episode.

    Args:
        store:      MemoryStore instance.
        session_id: If given, only process messages for this session.
        block_size: Number of messages per episode block.
        model:      LLM model ID for summarisation.
        client:     Optional pre-built boto3 client.

    Returns:
        Newly created Episode objects.
    """
    unprocessed = store.get_unprocessed_messages()
    if session_id:
        unprocessed = [m for m in unprocessed if m.session_id == session_id]

    if not unprocessed:
        return []

    # Group by session
    sessions: dict[str, List[Message]] = {}
    for msg in unprocessed:
        sessions.setdefault(msg.session_id, []).append(msg)

    created: List[Episode] = []
    for sid, msgs in sessions.items():
        # Sort by timestamp
        msgs.sort(key=lambda m: m.timestamp)

        # Chunk into blocks
        for i in range(0, len(msgs), block_size):
            block = msgs[i : i + block_size]
            summary = summarize_block(block, model=model, client=client)

            episode = Episode(
                session_id=sid,
                summary=summary,
                message_ids=[m.id for m in block if m.id is not None],
            )
            episode = store.add_episode(episode)

            # Back-link messages to this episode
            store.assign_episode(episode.message_ids, episode.id)  # type: ignore[arg-type]
            created.append(episode)

    return created
