"""
Stage 5: Publisher - Write skills, commit to git, create PRs.
"""
import subprocess
import os
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime
import json

from .models import SkillPackage, ValidationResult, PipelineConfig


class SkillWriter:
    """Write SKILL.md and supporting files to target directory."""

    def __init__(self, config: PipelineConfig):
        self.config = config

    def write(self, package: SkillPackage) -> Path:
        """Write skill package to disk."""
        # Determine output directory
        if self.config.output_skills_dir:
            skills_dir = Path(self.config.output_skills_dir)
        else:
            # Default to user-level ~/.openclaw/skills/
            skills_dir = Path(os.path.expanduser("~/.openclaw/skills/"))

        # Create skill directory
        skill_dir = skills_dir / package.skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)

        # Write SKILL.md
        skill_md_path = skill_dir / "SKILL.md"
        with open(skill_md_path, 'w') as f:
            f.write(package.skill_md_content)

        # Write supporting files
        for filename, content in package.supporting_files.items():
            file_path = skill_dir / filename
            with open(file_path, 'w') as f:
                f.write(content)

        # Write metadata
        metadata_path = skill_dir / ".skillforge_metadata.json"
        with open(metadata_path, 'w') as f:
            json.dump(package.metadata, f, indent=2)

        return skill_dir


class GitCommitter:
    """Git commit with structured message."""

    def __init__(self, config: PipelineConfig):
        self.config = config

    def commit(
        self,
        skill_dir: Path,
        package: SkillPackage,
        validation_result: ValidationResult
    ) -> str:
        """Create git commit for new skill."""
        if self.config.dry_run:
            return self._dry_run_commit(skill_dir, package)

        try:
            # Configure git author
            self._configure_git_author()

            # Add files
            subprocess.run(
                ['git', 'add', str(skill_dir)],
                check=True,
                capture_output=True,
                text=True
            )

            # Build commit message
            commit_msg = self._build_commit_message(package, validation_result)

            # Commit
            result = subprocess.run(
                ['git', 'commit', '-m', commit_msg],
                check=True,
                capture_output=True,
                text=True,
                cwd=skill_dir.parent.parent
            )

            # Get commit hash
            commit_hash = subprocess.run(
                ['git', 'rev-parse', 'HEAD'],
                check=True,
                capture_output=True,
                text=True,
                cwd=skill_dir.parent.parent
            ).stdout.strip()

            return commit_hash

        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Git commit failed: {e.stderr}")

    def _configure_git_author(self):
        """Configure git author for commits."""
        try:
            subprocess.run(
                ['git', 'config', 'user.name', self.config.git_author_name],
                check=True,
                capture_output=True
            )
            subprocess.run(
                ['git', 'config', 'user.email', self.config.git_author_email],
                check=True,
                capture_output=True
            )
        except subprocess.CalledProcessError:
            # Config might already be set, that's okay
            pass

    def _build_commit_message(
        self,
        package: SkillPackage,
        validation_result: ValidationResult
    ) -> str:
        """Build structured commit message."""
        lines = [
            f"Add skill: {package.skill_name}",
            "",
            f"Automatically generated by SkillForge",
            "",
            "Details:",
        ]

        # Add spec info if available
        if 'spec' in package.metadata:
            spec_data = package.metadata['spec']
            lines.append(f"  Root cause: {spec_data.get('root_cause', 'N/A')[:80]}")
            lines.append(f"  Priority: {spec_data.get('priority_score', 0.0)}")
            lines.append(f"  Classification: {spec_data.get('classification', 'unknown')}")

        # Add validation scores
        lines.append("")
        lines.append("Validation scores:")
        for key, value in validation_result.scores.items():
            lines.append(f"  {key}: {value:.2f}")

        # Add timestamp
        lines.append("")
        lines.append(f"Generated: {datetime.now().isoformat()}")

        return "\n".join(lines)

    def _dry_run_commit(self, skill_dir: Path, package: SkillPackage) -> str:
        """Simulate commit in dry-run mode."""
        return f"[DRY-RUN] Would commit skill at {skill_dir}"


class PRCreator:
    """Create GitHub PR using gh CLI."""

    def __init__(self, config: PipelineConfig):
        self.config = config

    def create_pr(
        self,
        skill_dir: Path,
        package: SkillPackage,
        commit_hash: str
    ) -> Optional[str]:
        """Create GitHub PR for skill."""
        if self.config.dry_run:
            return self._dry_run_pr(package)

        if not self.config.create_pr:
            return None

        try:
            # Check if gh CLI is available
            subprocess.run(
                ['gh', '--version'],
                check=True,
                capture_output=True
            )

            # Create branch name
            branch_name = f"skillforge/{package.skill_name}"

            # Create and checkout branch
            self._create_branch(branch_name, skill_dir.parent.parent)

            # Push branch
            self._push_branch(branch_name, skill_dir.parent.parent)

            # Create PR
            pr_url = self._create_github_pr(package, branch_name, skill_dir.parent.parent)

            return pr_url

        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"PR creation failed: {e.stderr if hasattr(e, 'stderr') else e}")
        except FileNotFoundError:
            # gh CLI not installed
            return None

    def _create_branch(self, branch_name: str, repo_dir: Path):
        """Create git branch."""
        try:
            # Create branch
            subprocess.run(
                ['git', 'checkout', '-b', branch_name],
                check=True,
                capture_output=True,
                cwd=repo_dir
            )
        except subprocess.CalledProcessError:
            # Branch might already exist, checkout
            subprocess.run(
                ['git', 'checkout', branch_name],
                check=True,
                capture_output=True,
                cwd=repo_dir
            )

    def _push_branch(self, branch_name: str, repo_dir: Path):
        """Push branch to remote."""
        subprocess.run(
            ['git', 'push', '-u', 'origin', branch_name],
            check=True,
            capture_output=True,
            cwd=repo_dir
        )

    def _create_github_pr(self, package: SkillPackage, branch_name: str, repo_dir: Path) -> str:
        """Create GitHub PR using gh CLI."""
        # Build PR title and body
        title = f"Add skill: {package.skill_name}"

        body_parts = [
            "## SkillForge Auto-Generated Skill",
            "",
            "This skill was automatically generated by SkillForge to address detected skill gaps.",
            "",
            "### Details",
        ]

        if 'spec' in package.metadata:
            spec_data = package.metadata['spec']
            body_parts.append(f"- **Root cause**: {spec_data.get('root_cause', 'N/A')}")
            body_parts.append(f"- **Priority**: {spec_data.get('priority_score', 0.0)}")
            body_parts.append(f"- **Classification**: {spec_data.get('classification', 'unknown')}")

        body_parts.extend([
            "",
            "### Review Required",
            "",
            "⚠️ **Human review required before merging**",
            "",
            "Please review the skill for:",
            "- Accuracy of instructions",
            "- Appropriateness of scope",
            "- No conflicts with existing skills",
            "- Proper validation scores",
            "",
            "---",
            "🤖 Generated by SkillForge"
        ])

        body = "\n".join(body_parts)

        # Create PR
        result = subprocess.run(
            [
                'gh', 'pr', 'create',
                '--base', self.config.pr_base_branch,
                '--head', branch_name,
                '--title', title,
                '--body', body
            ],
            check=True,
            capture_output=True,
            text=True,
            cwd=repo_dir
        )

        # Extract PR URL from output
        pr_url = result.stdout.strip()
        return pr_url

    def _dry_run_pr(self, package: SkillPackage) -> str:
        """Simulate PR creation in dry-run mode."""
        return f"[DRY-RUN] Would create PR for skill: {package.skill_name}"


class Publisher:
    """Main Publisher stage coordinator."""

    def __init__(self, config: PipelineConfig):
        self.config = config
        self.writer = SkillWriter(config)
        self.committer = GitCommitter(config)
        self.pr_creator = PRCreator(config)

    def run(
        self,
        package: SkillPackage,
        validation_result: ValidationResult
    ) -> Dict[str, Any]:
        """Run the Publisher stage."""
        deployment_metadata = {
            'skill_name': package.skill_name,
            'timestamp': datetime.now().isoformat(),
            'validation_scores': validation_result.scores,
            'dry_run': self.config.dry_run
        }

        try:
            # Write skill to disk
            skill_dir = self.writer.write(package)
            deployment_metadata['skill_dir'] = str(skill_dir)

            # Git commit
            if not self.config.mock_mode:
                commit_hash = self.committer.commit(skill_dir, package, validation_result)
                deployment_metadata['commit_hash'] = commit_hash

                # Create PR if enabled
                pr_url = self.pr_creator.create_pr(skill_dir, package, commit_hash)
                if pr_url:
                    deployment_metadata['pr_url'] = pr_url
            else:
                deployment_metadata['commit_hash'] = '[MOCK]'
                deployment_metadata['pr_url'] = '[MOCK]'

            deployment_metadata['status'] = 'success'

        except Exception as e:
            deployment_metadata['status'] = 'failed'
            deployment_metadata['error'] = str(e)

        return deployment_metadata


class DryRunPublisher:
    """Publisher that logs actions without writing."""

    def __init__(self, config: PipelineConfig):
        self.config = config

    def run(
        self,
        package: SkillPackage,
        validation_result: ValidationResult
    ) -> Dict[str, Any]:
        """Simulate publishing."""
        return {
            'skill_name': package.skill_name,
            'timestamp': datetime.now().isoformat(),
            'validation_scores': validation_result.scores,
            'dry_run': True,
            'status': 'simulated',
            'message': f"Would publish skill: {package.skill_name}"
        }
