/**
 * Guard: multi-tenant-auth
 * Multi-tenant SaaS authentication chain - ensures all database queries are validated, authenticated, and authorized
 * 
 * This file is auto-generated by VerifyLoop. Do not edit manually.
 */

declare const __brand: unique symbol;
type Brand<T, TBrand extends string> = T & { readonly [__brand]: TBrand };

/**
 * Unvalidated user input from HTTP request
 */
export type RawInput = Brand<{
  data: unknown;
}, 'RawInput'>;

/**
 * Input validated against schema
 * Requires: RawInput
 */
export type ValidatedInput = Brand<{
  userId: string;
  action: string;
  resource: string;
}, 'ValidatedInput'>;

/**
 * User authenticated with valid token
 * Requires: ValidatedInput
 */
export type AuthenticatedCtx = Brand<{
  userId: string;
  action: string;
  resource: string;
  sessionToken: string;
}, 'AuthenticatedCtx'>;

/**
 * Request authorized for specific tenant
 * Requires: AuthenticatedCtx
 */
export type AuthorizedQuery = Brand<{
  userId: string;
  action: string;
  resource: string;
  sessionToken: string;
  tenantId: string;
}, 'AuthorizedQuery'>;

// Constructors
export declare function createRawInput(data: unknown): RawInput;
export declare function validateInput(input: RawInput): ValidatedInput;
export declare function authenticate(input: ValidatedInput, sessionToken: string): AuthenticatedCtx;
export declare function authorizeQuery(input: AuthenticatedCtx, tenantId: string): AuthorizedQuery;

// Protected functions
export declare function dbQuery(input: AuthorizedQuery, ...args: unknown[]): Promise<unknown>;
export declare function dbWrite(input: AuthorizedQuery, ...args: unknown[]): Promise<unknown>;
export declare function dbDelete(input: AuthorizedQuery, ...args: unknown[]): Promise<unknown>;